import assert from 'node:assert/strict';
import { execFile as execute } from 'node:child_process';
import { cp, mkdtemp, readFile, rm, writeFile } from 'node:fs/promises';
import os from 'node:os'; import path from 'node:path'; import { promisify } from 'node:util'; import test from 'node:test';
import { authorizeTaskExecution } from '../scripts/lib/execution-authorization.mjs';
import { loadDeliveryHandoff, renderDeliveryHandoff } from '../scripts/lib/delivery-handoff.mjs';
import { profileProject } from '../scripts/lib/project-profiler.mjs';
import { compileContextCapsules, compileTaskGraph, sha256 } from '../scripts/lib/task-graph.mjs';
import { createHash } from 'node:crypto';
const execFile = promisify(execute); const hash = (value) => createHash('sha256').update(value).digest('hex');
const task = [{ task_id: 'tsk_handoff', title: 'Handoff fixture', objective: 'Prove delivery handoff.', slice: 'vertical', criterion_ids: ['ac_fixture'], depends_on: [], code_anchors: [{ path: 'src/app.tsx', reason: 'Fixture source.' }], verification: { commands: ['npm test'], proofs: ['Fixture proof.'] } }];
async function setup(t, mode = 'verified') {
  const root = await mkdtemp(path.join(os.tmpdir(), 'handoff-target-')); const records = await mkdtemp(path.join(os.tmpdir(), 'handoff-records-')); t.after(() => Promise.all([rm(root, { recursive: true, force: true }), rm(records, { recursive: true, force: true })]));
  await cp('tests/fixtures/project-profiler/node-web', root, { recursive: true }); await execFile('git', ['init', '-q'], { cwd: root }); await execFile('git', ['add', '.'], { cwd: root }); await execFile('git', ['-c', 'user.name=test', '-c', 'user.email=test@example.test', 'commit', '-qm', 'fixture'], { cwd: root });
  const profile = await profileProject(root); const contract = JSON.parse(await readFile('tests/fixtures/change-contract/valid-accepted.json', 'utf8')); contract.base_repository = { identity: 'fixture', ...profile.target };
  const graph = await compileTaskGraph({ graph_id: 'tgr_handoff', contract, targetPath: root, tasks: task }); const [capsule] = await compileContextCapsules(graph, contract, root); const authorization = await authorizeTaskExecution({ contract, graph, capsule, targetPath: root });
  const stopped = mode === 'stopped'; const execution = { schema_version: '1.0.0', event_id: 'exe_handoff_complete', kind: stopped ? 'stop' : 'complete', base_revision: profile.target.git_revision, task_id: capsule.task_id, worktree: { path: 'discarded-worktree', branch: null }, commands: [], file_changes: stopped ? [] : ['src/app.tsx'], result: { status: stopped ? 'stopped' : 'unverified_implementation', change_identity: stopped ? null : 'diff:handoff' } };
  const proofStatus = mode === 'partial' ? 'unverifiable' : mode === 'blocked' ? 'blocked' : 'proven'; const event = stopped ? null : { schema_version: '1.0.0', verification_event_id: 'ver_handoff', task_id: capsule.task_id, execution: { event_id: execution.event_id, change_identity: execution.result.change_identity }, verifier: { verifier_id: 'engineering-verifier', fresh_context_id: 'fresh-handoff', separate_from_executor: true, executor_reasoning_available: false }, status: proofStatus, rationale: 'Observed fixture result.', evidence: [{ category: 'command', summary: 'fixture check' }] };
  const proof = stopped ? null : { schema_version: '1.0.0', proof_id: 'prf_handoff', criterion_id: 'ac_fixture', verification_event_id: event.verification_event_id, execution: event.execution, verifier: event.verifier, status: proofStatus, rationale: 'Observed fixture result.', evidence: [{ category: 'command', summary: 'fixture check' }] };
  const values = { profile, contract, graph, capsule, authorization, execution_event: execution, verification_events: event ? [event] : [], criterion_proofs: proof ? [proof] : [] }; const refs = [];
  for (const [kind, value] of Object.entries(values)) { const name = `${kind}.json`; const raw = `${JSON.stringify(value, null, 2)}\n`; await writeFile(path.join(records, name), raw); refs.push({ kind, path: name, sha256: hash(raw) }); }
  const verification = { status: stopped ? 'not_run' : proofStatus, repair_rounds: 0, event_ids: event ? [event.verification_event_id] : [], proof_statuses: proof ? [{ criterion_id: proof.criterion_id, proof_id: proof.proof_id, status: proof.status, rationale: proof.rationale }] : [] };
  const manifest = { schema_version: '1.0.0', delivery_id: 'dlv_handoff', status: stopped ? 'stopped' : proofStatus === 'proven' ? 'verified' : proofStatus === 'blocked' ? 'blocked' : 'not_verified', accepted_decision_ids: capsule.decisions.map(({ decision_id }) => decision_id), tasks: { completed: [capsule.task_id], remaining: [] }, contract: { contract_id: contract.contract_id, sha256: sha256(contract) }, base_repository: profile.target, references: refs, final_change: { execution_event_id: execution.event_id, change_identity: execution.result.change_identity, changed_files: execution.file_changes }, verification, unresolved: proofStatus === 'blocked' ? [{ kind: 'blocker', statement: 'Fixture evidence is blocked.' }] : [], repair_history: [], integration: { status: 'not_applied', statement: 'No merge, push, or deployment occurred.' }, next_action: proofStatus === 'proven' ? 'Human reviews and applies the identified change before any merge.' : 'Revalidate and resolve the recorded terminal proof before another delivery attempt.' };
  const manifestPath = path.join(records, 'delivery-manifest.json'); await writeFile(manifestPath, `${JSON.stringify(manifest, null, 2)}\n`); return { root, records, manifest, manifestPath };
}

test('renders a deterministic verified handoff from canonical records without session history', async (t) => { const input = await setup(t); const first = renderDeliveryHandoff(await loadDeliveryHandoff(input.manifestPath, input.root)); const second = renderDeliveryHandoff(await loadDeliveryHandoff(input.manifestPath, input.root)); assert.equal(first, second); const { stdout } = await execFile('node', ['scripts/render-delivery-handoff.mjs', input.manifestPath, input.root]); assert.equal(stdout, first); assert.match(stdout, /Final diff identity: diff:handoff/); });
test('preserves partial and blocked verification rather than promoting them', async (t) => { for (const mode of ['partial', 'blocked']) { const input = await setup(t, mode); const output = renderDeliveryHandoff(await loadDeliveryHandoff(input.manifestPath, input.root)); assert.match(output, mode === 'partial' ? /Status: \*\*not_verified\*\*/ : /Status: \*\*blocked\*\*/); assert.doesNotMatch(output, /Verification: proven/); } });
test('preserves a stopped handoff without inventing a change or proof', async (t) => { const input = await setup(t, 'stopped'); const output = renderDeliveryHandoff(await loadDeliveryHandoff(input.manifestPath, input.root)); assert.match(output, /Status: \*\*stopped\*\*/); assert.match(output, /Final diff identity: none/); assert.match(output, /No verification ran/); });
test('fails closed for target drift and missing canonical references', async (t) => { const drifted = await setup(t); await writeFile(path.join(drifted.root, 'src', 'app.tsx'), 'drift\n'); await assert.rejects(() => loadDeliveryHandoff(drifted.manifestPath, drifted.root), /stale/); const missing = await setup(t); missing.manifest.references[0].path = 'missing.json'; await writeFile(missing.manifestPath, `${JSON.stringify(missing.manifest, null, 2)}\n`); await assert.rejects(() => loadDeliveryHandoff(missing.manifestPath, missing.root), /Missing canonical reference/); });
