import assert from 'node:assert/strict';
import { execFile as execute } from 'node:child_process';
import { cp, mkdtemp, readFile, rm, writeFile } from 'node:fs/promises';
import os from 'node:os'; import path from 'node:path'; import { promisify } from 'node:util'; import test from 'node:test';
import { authorizeClassification, authorizeTaskExecution, classifyRisk, validateExecutionAuthorization, validateRiskClassification } from '../scripts/lib/execution-authorization.mjs';
import profileFixture from './fixtures/production-risk-profiles.json' with { type: 'json' };
import { compileContextCapsules, compileTaskGraph } from '../scripts/lib/task-graph.mjs'; import { profileProject } from '../scripts/lib/project-profiler.mjs';
const execFile = promisify(execute);
const task = () => [{ task_id: 'tsk_fixture', title: 'Vertical fixture', objective: 'Prove one slice.', slice: 'vertical', criterion_ids: ['ac_fixture'], depends_on: [], code_anchors: [{ path: 'src/app.tsx', reason: 'Fixture source.' }], verification: { commands: ['npm test'], proofs: ['Fixture proof.'] } }];
async function setup(t) { const root = await mkdtemp(path.join(os.tmpdir(), 'authorization-')); t.after(() => rm(root, { recursive: true, force: true })); await cp('tests/fixtures/project-profiler/node-web', root, { recursive: true }); await execFile('git', ['init', '-q'], { cwd: root }); await execFile('git', ['add', '.'], { cwd: root }); await execFile('git', ['-c', 'user.name=test', '-c', 'user.email=test@example.test', 'commit', '-qm', 'fixture'], { cwd: root }); const contract = JSON.parse(await readFile('tests/fixtures/change-contract/valid-accepted.json', 'utf8')); contract.base_repository = { identity: 'fixture', ...(await profileProject(root)).target }; const graph = await compileTaskGraph({ graph_id: 'tgr_fixture', contract, targetPath: root, tasks: task() }); const [capsule] = await compileContextCapsules(graph, contract, root); return { root, contract, graph, capsule }; }

test('keeps low-risk reversible work lightweight while recording fixed invalidation and human merge/deploy boundaries', async (t) => { const { root, contract, graph, capsule } = await setup(t); const result = await authorizeTaskExecution({ contract, graph, capsule, targetPath: root }); assert.equal(result.status, 'authorized'); assert.equal(result.classification.overall_level, 'low'); assert.equal(result.allowed_autonomy, 'bounded_agent'); assert.equal(result.isolation, 'current_worktree'); assert.deepEqual(result.verification_categories, ['task_verification']); assert.deepEqual(result.human_approval_boundaries, ['before_merge', 'before_deployment']); });

test('rejects draft contracts, unresolved uncertainty, stale profile/base, stale capsule, and malformed records', async (t) => { const { root, contract, graph, capsule } = await setup(t); const draft = structuredClone(contract); draft.lifecycle_state = 'draft'; await assert.rejects(() => authorizeTaskExecution({ contract: draft, graph, capsule, targetPath: root }), /denied|accepted/); const unresolved = structuredClone(contract); unresolved.uncertainties.push({ ...structuredClone(unresolved.uncertainties[0]), uncertainty_id: 'unc_required', status: 'unresolved', downstream_dependency: true }); await assert.rejects(() => authorizeTaskExecution({ contract: unresolved, graph, capsule, targetPath: root }), /denied|accepted|validation/); const stale = structuredClone(capsule); stale.base_repository.source_fingerprint = '0'.repeat(64); await assert.rejects(() => authorizeTaskExecution({ contract, graph, capsule: stale, targetPath: root }), /drift/); const classification = classifyRisk({ contract, graph, capsule }); classification.overall_level = 'high'; assert.equal(validateRiskClassification(classification).valid, false); const authorization = authorizeClassification(classifyRisk({ contract, graph, capsule }), capsule); authorization.human_approval_boundaries = ['before_merge']; assert.equal(validateExecutionAuthorization(authorization).valid, false); });

test('requires high-risk controls and rejects excessive autonomy or contradictory controls', async (t) => { const { root, contract, graph, capsule } = await setup(t); const high = await authorizeTaskExecution({ contract, graph, capsule, targetPath: root, signals: { migrations: { level: 'high', rationale: 'Irreversible schema conversion.' }, security_authentication_authorization: { level: 'high', rationale: 'Authorization boundary changes.' } } }); assert.equal(high.allowed_autonomy, 'none'); assert.equal(high.isolation, 'isolated_worktree'); assert.ok(high.human_approval_boundaries.includes('before_execution')); assert.ok(high.verification_categories.includes('independent_review')); assert.ok(high.verification_categories.includes('migration_proof')); assert.ok(high.verification_categories.includes('security_review')); const excessive = structuredClone(high); excessive.allowed_autonomy = 'bounded_agent'; excessive.tool_posture = 'narrow_write'; assert.equal(validateExecutionAuthorization(excessive).valid, false); await writeFile(path.join(root, 'src', 'app.tsx'), 'drift\n'); await assert.rejects(() => authorizeTaskExecution({ contract, graph, capsule, targetPath: root }), /drift/); });

test('activates only relevant production profiles and rejects stripped gates', async (t) => { const { root, contract, graph, capsule } = await setup(t); const low = await authorizeTaskExecution({ contract, graph, capsule, targetPath: root }); assert.deepEqual(low.profile_gates, []); for (const [dimension, profile] of profileFixture.profiles) { const authorization = await authorizeTaskExecution({ contract, graph, capsule, targetPath: root, signals: { [dimension]: { level: 'low', rationale: `${profile} applies.` } } }); assert.deepEqual(authorization.profile_gates.map(({ profile_id }) => profile), [profile]); assert.ok(authorization.verification_categories.includes(authorization.profile_gates[0].verification_categories[0])); }
  const combined = await authorizeTaskExecution({ contract, graph, capsule, targetPath: root, signals: { migrations: { level: 'high', rationale: 'Migration applies.' }, dependency_introduction: { level: 'low', rationale: 'Dependency applies.' } } }); assert.equal(combined.allowed_autonomy, 'none'); assert.deepEqual(combined.profile_gates.map(({ profile_id }) => profile_id), profileFixture.combination); const bypass = structuredClone(combined); bypass.profile_gates = []; assert.equal(validateExecutionAuthorization(bypass).valid, false); });
