import assert from 'node:assert/strict';
import test from 'node:test';
import { projectFocusedResearchInput, acceptFocusedResearchEvidence } from '../scripts/lib/focused-engineering-research.mjs';
import need from './fixtures/evidence-router/simple-external.json' with { type: 'json' };

const input = projectFocusedResearchInput(need, { repositoryEvidence: { observed_facts: ['ajv is declared.'], unresolved_subquestions: [] }, authoritativeEvidence: { result: { status: 'unavailable', records: [] }, provenance: { locator: 'not retrieved' }, unresolved_gaps: ['T1 unavailable'] } });
const source = { source_id: 'frs_docs', title: 'Official release notes', publisher: 'Vendor', publication_date: '2026-01-01T00:00:00.000Z', publication_unavailable_reason: null, locator: 'https://vendor.test/releases#8.20.0', source_type: 'official_release', accessed_at: '2026-08-02T00:00:00.000Z', independence_group: 'vendor', version_applicability: '8.20.0' };
const evidence = { schema_version: '1.0.0', evidence_id: 'fre_external', knowledge_need_id: input.knowledge_need.knowledge_need_id, scope: { question: input.knowledge_need.question, repository: input.knowledge_need.scope.repository, dependencies: input.knowledge_need.scope.dependencies, versions: input.knowledge_need.scope.versions, usage: input.knowledge_need.scope.usage }, sources: [source], claims: [{ claim_id: 'frc_release', statement: 'Version 8.20.0 was released on 2026-01-01.', scope: 'The requested dependency release.', claim_type: 'source_assertion', confidence: 'medium', confidence_rationale: 'One official release record; no independent confirmation was needed for this narrow date lookup.', supporting_evidence: [{ source_id: source.source_id, locator: 'Release table, row 8.20.0' }], counter_evidence: [] }], unresolved_gaps: [], escalation: { required: false, tier: 'none', reasons: [] }, budget: { max_sources: 5, max_claims: 5, max_web_fetches: 10, used_sources: 1, used_claims: 1, used_web_fetches: 1 }, non_authorizing: true };

test('projection excludes unrelated context and permits one bounded researcher', () => { assert.equal(input.limits.max_external_researchers, 1); assert.equal(input.knowledge_need.why_it_matters, undefined); assert.equal(input.prior_facts.repository.observed_facts.length, 1); });
test('authoritative focused evidence validates and remains non-authorizing', () => { assert.equal(acceptFocusedResearchEvidence(input, evidence).valid, true); });
test('low-confidence evidence must escalate', () => { const low = structuredClone(evidence); low.claims[0].confidence = 'low'; low.escalation = { required: false, tier: 'none', reasons: [] }; assert.equal(acceptFocusedResearchEvidence(input, low).valid, false); });
test('unknown source references fail closed', () => { const bad = structuredClone(evidence); bad.claims[0].supporting_evidence[0].source_id = 'frs_missing'; assert.equal(acceptFocusedResearchEvidence(input, bad).valid, false); });
test('source and claim budgets are hard limits', () => { const over = structuredClone(evidence); over.budget.used_web_fetches = 11; assert.equal(acceptFocusedResearchEvidence(input, over).valid, false); });
