import assert from 'node:assert/strict';
import { cp, mkdtemp, readFile, rm } from 'node:fs/promises';
import os from 'node:os';
import path from 'node:path';
import { execFile as execute } from 'node:child_process';
import { promisify } from 'node:util';
import test from 'node:test';
import { authorizeTaskExecution } from '../scripts/lib/execution-authorization.mjs';
import { compileContextCapsules, compileTaskGraph } from '../scripts/lib/task-graph.mjs';
import { profileProject } from '../scripts/lib/project-profiler.mjs';
import { verifyAuthorizedTask } from '../scripts/lib/task-verifier.mjs';

const execFile = promisify(execute);
const task = () => [{ task_id: 'tsk_verify', title: 'Verify fixture', objective: 'Prove fixture behavior.', slice: 'vertical', criterion_ids: ['ac_fixture'], depends_on: [], code_anchors: [{ path: 'src/app.tsx', reason: 'Fixture source.' }], verification: { commands: ['npm test'], proofs: ['Fixture test passes.'] } }];
async function setup(t) { const root = await mkdtemp(path.join(os.tmpdir(), 'task-verifier-')); t.after(() => rm(root, { recursive: true, force: true })); await cp('tests/fixtures/project-profiler/node-web', root, { recursive: true }); await execFile('git', ['init', '-q'], { cwd: root }); await execFile('git', ['add', '.'], { cwd: root }); await execFile('git', ['-c', 'user.name=test', '-c', 'user.email=test@example.test', 'commit', '-qm', 'fixture'], { cwd: root }); const contract = JSON.parse(await readFile('tests/fixtures/change-contract/valid-accepted.json', 'utf8')); contract.base_repository = { identity: 'fixture', ...(await profileProject(root)).target }; const graph = await compileTaskGraph({ graph_id: 'tgr_verify', contract, targetPath: root, tasks: task() }); const [capsule] = await compileContextCapsules(graph, contract, root); const authorization = await authorizeTaskExecution({ contract, graph, capsule, targetPath: root, signals: {} }); const executionEvent = { schema_version: '1.0.0', event_id: 'exe_tsk_verify_complete', kind: 'complete', base_revision: capsule.base_repository.git_revision, task_id: capsule.task_id, worktree: { path: root, branch: null }, commands: [{ argv: ['fixture-executor'], exit_code: 0 }], file_changes: ['src/app.tsx'], result: { status: 'unverified_implementation', change_identity: 'diff:fixture' } }; return { contract, graph, capsule, authorization, executionEvent }; }
const result = ({ input, status = 'proven', categories = ['command'], id = 'ver_tsk_verify_0' }) => ({ event: { schema_version: '1.0.0', verification_event_id: id, task_id: input.capsule.task_id, execution: { event_id: input.execution_event.event_id, change_identity: input.change_identity }, verifier: { verifier_id: 'engineering-verifier', fresh_context_id: `fresh-${id}`, separate_from_executor: true, executor_reasoning_available: false }, status, rationale: 'Observed independently.', evidence: [{ category: categories[0], summary: 'Observed local result.' }] }, proofs: input.capsule.acceptance_criteria.map((criterion) => ({ schema_version: '1.0.0', proof_id: `prf_${criterion.criterion_id}_${id}`, criterion_id: criterion.criterion_id, verification_event_id: id, execution: { event_id: input.execution_event.event_id, change_identity: input.change_identity }, verifier: { verifier_id: 'engineering-verifier', fresh_context_id: `fresh-${id}`, separate_from_executor: true, executor_reasoning_available: false }, status, rationale: 'Observed independently.', evidence: categories.map((category) => ({ category, summary: 'Observed local result.' })) })) });

test('independent fresh-context verification proves every criterion without changing executor approval', async (t) => { const input = await setup(t); const output = await verifyAuthorizedTask({ ...input, runVerifier: async ({ input: context }) => result({ input: context }) }); assert.equal(output.status, 'verified'); assert.equal(output.repair_rounds, 0); assert.equal(output.events.length, 1); assert.ok(Object.isFrozen(output.proofs)); });

test('rejects executor self-approval, unsupported criteria, stale identities, and runtime proof theater', async (t) => { const input = await setup(t); await assert.rejects(() => verifyAuthorizedTask({ ...input, verifierAgentId: 'engineering-executor', runVerifier: async () => null }), /distinct/); await assert.rejects(() => verifyAuthorizedTask({ ...input, runVerifier: async ({ input: context }) => { const output = result({ input: context }); output.proofs[0].criterion_id = 'ac_unsupported'; return output; } }), /invalid|unsupported|fresh-context/); await assert.rejects(() => verifyAuthorizedTask({ ...input, runVerifier: async ({ input: context }) => { const output = result({ input: context }); output.event.execution.change_identity = 'diff:stale'; return output; } }), /stale/); const runtime = { ...input, capsule: structuredClone(input.capsule) }; runtime.capsule.acceptance_criteria[0].required_proof_kinds = ['runtime']; await assert.rejects(() => verifyAuthorizedTask({ ...runtime, runVerifier: async ({ input: context }) => result({ input: context, categories: ['command'] }) }), /required proof/); });

test('rejects a proven result that bypasses an activated production-profile proof gate', async (t) => { const input = await setup(t); input.authorization = await authorizeTaskExecution({ contract: input.contract, graph: input.graph, capsule: input.capsule, targetPath: input.executionEvent.worktree.path, signals: { external_apis: { level: 'low', rationale: 'Outbound API behavior changes.' } } }); await assert.rejects(() => verifyAuthorizedTask({ ...input, runVerifier: async ({ input: context }) => result({ input: context }) }), /external_api_integration lacks required proof/); const output = await verifyAuthorizedTask({ ...input, runVerifier: async ({ input: context }) => result({ input: context, categories: ['command', 'api'] }) }); assert.equal(output.status, 'verified'); });

test('uses only bounded targeted repairs and leaves exhausted failures transparent', async (t) => { const input = await setup(t); let calls = 0; const output = await verifyAuthorizedTask({ ...input, runVerifier: async ({ input: context, attempt }) => { calls += 1; return result({ input: context, status: 'failed', id: `ver_tsk_verify_${attempt}` }); }, runRepair: async ({ change_identity }) => ({ change_identity: `${change_identity}-repair-${calls}` }) }); assert.equal(output.status, 'not_verified'); assert.equal(output.repair_rounds, 2); assert.equal(calls, 3); assert.equal(output.events.length, 3); assert.equal(output.proofs[0].status, 'failed'); });
